// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWiG8yJY5a6cRIOq8VOBHzi4HKT3SJ26s',
    appId: '1:433616123405:web:99c4519c0353dc3ec3c744',
    messagingSenderId: '433616123405',
    projectId: 'asesoriasitam',
    authDomain: 'asesoriasitam.firebaseapp.com',
    storageBucket: 'asesoriasitam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkDh-LVt1xrsRYnXKLJQ4Y781j3NCr94',
    appId: '1:433616123405:android:5990bdc1d6384131c3c744',
    messagingSenderId: '433616123405',
    projectId: 'asesoriasitam',
    storageBucket: 'asesoriasitam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrKlvNNRyjGacSncS43-USpftX5EfcJ3U',
    appId: '1:433616123405:ios:7b4df4b9a7b694e4c3c744',
    messagingSenderId: '433616123405',
    projectId: 'asesoriasitam',
    storageBucket: 'asesoriasitam.appspot.com',
    iosClientId: '433616123405-j21j6rsrtmovvuof7hk0m67s6jbvqn7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.asesoriasitam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrKlvNNRyjGacSncS43-USpftX5EfcJ3U',
    appId: '1:433616123405:ios:7b4df4b9a7b694e4c3c744',
    messagingSenderId: '433616123405',
    projectId: 'asesoriasitam',
    storageBucket: 'asesoriasitam.appspot.com',
    iosClientId: '433616123405-j21j6rsrtmovvuof7hk0m67s6jbvqn7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.asesoriasitam',
  );
}
